image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Ionic & Firebase CLI
    init: |
      npm i -g @ionic/cli @angular/cli firebase-tools
    command: firebase login --no-localhost && cd functions && npm i && cd ../